apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter-master
spec:
  template:
    metadata:
      labels:
        app: jmeter-master
    spec:
      restartPolicy: Never
      containers:
      - name: jmeter
        image: nihal2897577/my-jmeter:latest # Isko bhi apne DockerHub username se replace karna hoga
        command: ["/bin/sh", "-c"]
        args:
          - jmeter -n -t /script/test-script.jmx -R jmeter-workers -Gthreads=500 -l /results/results.jtl;
            sleep 300; # Test khatam hone ke baad container 5 minute zinda rahega taaki Jenkins results download kar sake
        volumeMounts:
        - name: script-volume
          mountPath: /script
        - name: results-volume
          mountPath: /results
      volumes:
      - name: script-volume
        configMap:
          name: jmeter-script-config # Yeh wahi configmap hai jo Jenkins banayega
      - name: results-volume
        emptyDir: {}