apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter-master
spec:
  template:
    metadata:
      labels:
        app: jmeter-master
    spec:
      restartPolicy: Never
      containers:
      - name: jmeter
        image: nihal2897577/my-jmeter:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            # 1. DNS se saare worker pods ki IPs nikal kar comma se separate karna
            WORKER_IPS=$(getent ahosts jmeter-workers | awk '{print $1}' | sort -u | tr '\n' ',' | sed 's/,$//')
            echo "Resolved Worker IPs: $WORKER_IPS"
            
            # 2. JMeter command ko dynamic IPs ke sath chalana
            jmeter -n -t /script/test-script.jmx -R $WORKER_IPS -Gthreads=20 -Dserver.rmi.ssl.disable=true -l /results/results.jtl -e -o /results/html-report
            
            # 3. Jenkins ke copy karne ke liye wait karna
            sleep 60
        volumeMounts:
        - name: script-volume
          mountPath: /script
        - name: results-volume
          mountPath: /results
      volumes:
      - name: script-volume
        configMap:
          name: jmeter-script-config
      - name: results-volume
        emptyDir: {}
